version: '2.1'

services:
  icade_immo_db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - icade_immo_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  icade_immo_web:
    build:
      context: .
      dockerfile: "./Dockerfile.dev"
    ports:
      - "5002:5000"
    depends_on:
      icade_immo_db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./Pipfile:/app/Pipfile
      - ./uploaded_media:/app/src/media:z
      - ./entrypoint.sh:/app/entrypoint.sh
      #- ./Pipfile.lock:/app/Pipfile.lock
    env_file:
      - ./.env
    tty: true
  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080

volumes:
  icade_immo_data: