from python:3.9-slim

label maintainer="Faouzi ben salah <ben.salah.mouhamed.faouzi@gmail.com>"

RUN apt update && apt install --no-install-recommends --no-install-suggests -y python-setuptools build-essential software-properties-common \
      libpq-dev libjpeg-dev zlib1g-dev \
      libpcre3 libpcre3-dev \
      && rm -rf /var/lib/apt/lists/*

env pythonpath=/app
env pythonunbuffered 1

run addgroup --system django \
    && adduser --system --ingroup django django

copy ./requirements.txt /requirements.txt

run pip install --upgrade pip \
    && pip install --no-cache-dir -r /requirements.txt

copy --chown=django:django ./src /app/src

user django

workdir /app

expose 8080

copy ./entrypoint.sh /entrypoint.sh
entrypoint /entrypoint.sh
